services:
  jellyfin: # Media Manager
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "${USER_ID}:${USER_ID}"
    ports:
      - 0.0.0.0:8096:8096/tcp
      - 0.0.0.0:7359:7359/udp
    volumes:
      - type: bind
        source: ${JELLYFIN_CONFIG_SOURCE}
        target: /config
      - type: bind
        source: ${JELLYFIN_CACHE_SOURCE}
        target: /cache
      - type: bind
        source: ${JELLYFIN_MEDIA_SOURCE}
        target: /media
      - type: bind
        source: ${JELLYFIN_FONTS_SOURCE}
        target: /fonts
    restart: 'unless-stopped'
  seerr: # Meant to discover media + request media
    image: seerr/seerr
    user: "${USER_ID}:${USER_ID}"
    init: true
    container_name: seerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TIMEZONE}
      - WEBUI_PORT=6880
      - TORRENTING_PORT=6881
    ports:
      - 0.0.0.0:5055:5055
    volumes:
      - type: bind
        source: ${SEERR_CONFIG_SOURCE}
        target: /app/config
    restart: 'unless-stopped'
  radarr: # Meant to process MOVIE media requests
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    user: "${USER_ID}:${USER_ID}"
    environment:
      - TZ=${TIMEZONE}
    ports:
      - 7878:7878
    volumes:
      - ${RADARR_CONFIG_SOURCE}:/config
      - ${JELLYFIN_MEDIA_SOURCE}:/data
    restart: 'unless-stopped'
  qbittorrent: # Downloads Client
    image: lscr.io/linuxserver/qbittorrent
    container_name: jellyfin-download-client-qbittorrent
    user: "${USER_UD}:${USER_ID}"
    environment:
      - PUID=${USER_ID}
      - PGUID=${USER_ID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=6880
      - TORRENTING_PORT=6881
    ports:
      - 0.0.0.0:6880:6880 # WEB UI
      - 0.0.0.0:6881:6881 # Torrent Protocol Ports
      - 0.0.0.0:6881:6881/udp
    volumes:
      - ${JELLYFIN_MEDIA_SOURCE}:/downlaods
      - ${QBITTORRENT_CONFIG_SOURCE}:/config
    restart: 'unless-stopped'
